dist: trusty
sudo: false

language: node_js
node_js:
  - '12'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - ./node_modules
install:
  - npm install
script:
  - npm run coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
