language: node_js
node_js:
  - '12'
addons:
  chrome: stable
dist: trusty
sudo: required

before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run coverage
  - ng build --prod
after_success:
  - bash <(curl -s https://codecov.io/bash)
