language: node_js
node_js:
  - '12'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
dist: trusty
sudo: required

before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
