language: node_js
node_js:
  - '12'
addons:
  chrome: stable
dist: trusty
sudo: required

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g typescript
  - npm install -g @angular/cli

script:
  - npm install
  - ng lint
  - npm run coverage
  - ng build --prod

after_success:
  - bash <(curl -s https://codecov.io/bash)
