language: node_js
node_js:
  - "12"
dist: trusty
sudo: required

before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
