language: node_js

node_js:
  - '14.15.5'

addons:
  chrome: stable
dist: trusty

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g firebase-tools
  - npm install -g typescript
  - npm install -g @angular/cli
  - npm install
  - npm install codecov -g

script:
  - ng lint
  - npm run test-coverage

after_success:
  - codecov
  - ng build --prod
  - firebase deploy --token $FIREBASE_TOKEN
