language: node_js

env:
  - CODACY_PROJECT_TOKEN="a826990e6f64474685332c0e7c48b382"

node_js:
  - '12.18.2'

addons:
  chrome: stable
dist: trusty

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g typescript
  - npm install -g @angular/cli
  - npm install

script:
  - ng lint
  - npm run coverage

after_success:
  - ng build --prod
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report
